---
#playbook to install Flens Agent on Windows

- name: Create the Telegraf Directory
  win_file:
    path: C:\Program Files\InfluxData\Telegraf\
    state: directory

- name: Copy Telegraf executable from Ansible Server
  win_copy:
    src: telegraf.exe
    dest: C:\Program Files\InfluxData\Telegraf\

- name: Copy config file
  win_copy:
    src: telegraf.conf.{{ ansible_hostname }}
    dest: C:\Program Files\InfluxData\Telegraf\telegraf.conf

- name: Create the service with Powershell
  win_shell: |
     cd "C:\Program Files\InfluxData\Telegraf"; .\Telegraf.exe --service install --config 'C:\Program Files\InfluxData\Telegraf\telegraf.conf'

- name: Start the Windows Service
  win_service:
    name: telegraf
    start_mode: auto
    state: started